# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
description: >- # this means to ignore newlines until "baseurl:"
  Students visualize scientific data from a wide variety of sources, perform
  data analysis and dimensionality reduction using clustering techniques,
  understand system dynamics through differential equation approximation
  and agent-based modeling, construct probabilistic Monte-Carlo simulation models,
  and optimize continuous and discrete problems with local search techniques.
  Topics may include Markov models, bioinformatics, and signal processing.
  Each assignment requires writing a clear and coherent data analysis report
  that properly characterizes legitimate conclusions to be drawn from the data.
baseurl: "/csci285" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

number: CSCI 285
title: Scientific Computing
semester: Fall 2022

navigation:
  - title: Overview
    subfolderitems:
      - page: Description
        url: '#description'
      - page: Learning Goals
        url: '#goals'
      - page: Attendance
        url: '#attendance'
      - page: Checkins
        url: '#checkins'
      - page: Late Work Policy
        url: '#latework'
      - page: Resources
        url: '#resources'
  - title: Coursework
    subfolderitems:
      - page: Labs
        url: '#labs'
      - page: Exams
        url: '#exams'
      - page: Final Project
        url: '#project'
  - page: Calendar
    url: '#calendar'
  - page: Commitments
    url: '#commitments'

instructors:
  - id: wilson
    name: Prof. Joshua Wilson
    email: wilsonj@hendrix.edu
    phone: (919) 323-6369

offerings:
  - name: LECTURE 01
    loc: MCREY 315
    time: TR 2:45 - 4:00pm
    instructor: wilson

resources:
  - name: Python 3
    image: assets/images/pythonlogo.png
    url: http://python.org
  - name: Anaconda
    image: assets/images/anaconda.png
    url: https://www.anaconda.com/products/individual
  - name: Pandas
    image: assets/images/pandas.png
    url: https://pandas.pydata.org/
  - name: Matplotlib
    image: assets/images/matplotlib.png
    url: https://plotnine.readthedocs.io/en/stable/
  - name: Mesa
    image: assets/images/mesa_logo.png
    url: https://mesa.readthedocs.io/en/master/#

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
